(function(){
'use strict';
const products=[
{id:1,name:'Italian Olive Oil',category:'Grocery',price:620,emoji:'🫒',desc:'Smooth extra-virgin olive oil for everyday cooking.',tag:'Pantry pick'},
{id:2,name:'Garden Pasta',category:'Grocery',price:180,emoji:'🍝',desc:'Comfort-food pasta for simple weeknight meals.',tag:'Bestseller'},
{id:3,name:'Citrus Biscotti',category:'Snacks',price:240,emoji:'🍪',desc:'Crisp citrus biscuits made for tea-time.',tag:'Treat'},
{id:4,name:'Honey Granola',category:'Snacks',price:310,emoji:'🥣',desc:'Toasty oats, honey and a light crunch.',tag:'New'},
{id:5,name:'Linen Dish Cloth',category:'Home',price:150,emoji:'🧺',desc:'Soft reusable cloth for everyday kitchen care.',tag:'Useful'},
{id:6,name:'Herbal Hand Wash',category:'Care',price:280,emoji:'🧴',desc:'Gentle everyday hand wash with a clean finish.',tag:'Gentle'},
{id:7,name:'Tomato Passata',category:'Grocery',price:220,emoji:'🍅',desc:'Rich tomato base for pasta, soups and sauces.',tag:'Classic'},
{id:8,name:'Lavender Soap',category:'Care',price:170,emoji:'🧼',desc:'Mild soap bar with a soft botanical feel.',tag:'Simple'},
{id:9,name:'Basmati Rice',category:'Grocery',price:390,emoji:'🍚',desc:'Fragrant rice for everyday family meals.',tag:'Staple'},
{id:10,name:'Roasted Nuts',category:'Snacks',price:260,emoji:'🥜',desc:'Crunchy roasted nuts for a quick bite.',tag:'Popular'},
{id:11,name:'Laundry Powder',category:'Home',price:460,emoji:'🧺',desc:'Everyday fabric care for home laundry.',tag:'Home'},
{id:12,name:'Aloe Body Lotion',category:'Care',price:360,emoji:'🧴',desc:'Light daily moisturizer with aloe freshness.',tag:'Care'}
];
const demoReports=[
{type:'Cat',severity:'Urgent',country:'Bangladesh',location:'Rajshahi city',notes:'Needs roadside assistance; local community report.',time:Date.now()-4*60*1000},
{type:'Dog',severity:'High',country:'Bangladesh',location:'Dhaka neighborhood',notes:'Stray dog reported near a busy road.',time:Date.now()-13*60*1000},
{type:'Bird',severity:'Normal',country:'Bangladesh',location:'Saidpur area',notes:'Bird found unable to fly; observation requested.',time:Date.now()-28*60*1000}
];
const operators={Bangladesh:'Country route: Bangladesh · verified operator directory placeholder',India:'Country route: India · verified operator directory placeholder',Pakistan:'Country route: Pakistan · verified operator directory placeholder',Nepal:'Country route: Nepal · verified operator directory placeholder','Sri Lanka':'Country route: Sri Lanka · verified operator directory placeholder',Other:'Country route: manual operator selection required'};
let activeFilter='All',cart=[],reports=[],orders=[],lastReport=null,geo=null;
const $=id=>document.getElementById(id);
const safeStore={get(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(_){return f}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){return false}}};
cart=safeStore.get('pantry-cart',[]); if(!Array.isArray(cart)) cart=[];
orders=safeStore.get('pantry-orders',[]); if(!Array.isArray(orders)) orders=[];
reports=safeStore.get('pantry-rescue-reports',[]); if(!Array.isArray(reports)) reports=[];
function money(n){return '৳'+Number(n).toLocaleString('en-BD')}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2400)}
function nowText(){return new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dhaka',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())}
function updateClock(){const d=new Date();$('bdTime').textContent=nowText();$('todayText').textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dhaka',day:'2-digit',month:'short',year:'numeric'}).format(d);$('rescueDeskClock').textContent=nowText();$('heroUpdated').textContent='Updated '+nowText();}
function renderProducts(){const q=($('searchInput').value||'').toLowerCase();const sort=$('sortSelect').value;let list=products.filter(p=>(activeFilter==='All'||p.category===activeFilter)&&(p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)||p.desc.toLowerCase().includes(q)));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);$('productGrid').innerHTML=list.length?list.map(p=>`<article class="product-card" data-product="${p.id}"><div class="product-visual"><span class="pill">${p.tag}</span><span>${p.emoji}</span></div><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><span class="price">${money(p.price)}</span><div class="product-actions"><button class="details-btn" data-detail="${p.id}">Details</button><button class="add-btn" data-add="${p.id}">Add</button></div></div></article>`).join(''):`<div class="cart-empty" style="grid-column:1/-1">No products match that search.</div>`;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(Number(b.dataset.add)));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openProduct(Number(b.dataset.detail)));$('productCount').textContent=products.length;$('catalogStatus').textContent=`${list.length} matching products · Live catalog`}
function add(id){const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});persistCart();toast('Added to your Pantry cart')}
function change(id,delta){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=delta;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);persistCart()}
function persistCart(){safeStore.set('pantry-cart',cart);renderCart()}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0);$('cartCount').textContent=count;if(!cart.length){$('cartItems').innerHTML='<div class="cart-empty">Your cart is waiting for a little grocery magic. ✦</div>';$('cartTotal').textContent=money(0);$('checkoutTotal').textContent=money(0);return}$('cartItems').innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id);return `<div class="cart-line"><div class="cart-thumb">${p.emoji}</div><div><strong>${p.name}</strong><small>${money(p.price)} each</small><div class="qty"><button data-minus="${p.id}">−</button><span>${x.qty}</span><button data-plus="${p.id}">+</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`}).join('');document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>change(+b.dataset.plus,1));document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(+b.dataset.minus,-1));const total=cart.reduce((s,x)=>s+(products.find(y=>y.id===x.id)||{price:0}).price*x.qty,0);$('cartTotal').textContent=money(total);$('checkoutTotal').textContent=money(total)}
function openDrawer(id){closeAll();$(id).classList.add('open');$('overlay').classList.add('active')}
function closeDrawer(id){$(id).classList.remove('open');if(!document.querySelector('.drawer.open'))$('overlay').classList.remove('active')}
function closeAll(){document.querySelectorAll('.drawer.open').forEach(d=>d.classList.remove('open'));$('overlay').classList.remove('active')}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('productTitle').textContent=p.name;$('productDetail').innerHTML=`<div class="detail-visual">${p.emoji}</div><p class="muted-line">${p.category} · ${p.tag}</p><p>${p.desc}</p><div class="detail-price">${money(p.price)}</div><button class="btn btn-dark full" id="detailAddBtn">Add to cart</button>`;$('detailAddBtn').onclick=()=>{add(p.id);closeDrawer('productDrawer')};openDrawer('productDrawer')}
function renderOrders(){if(!orders.length){$('ordersList').innerHTML='<div class="empty-panel">No orders yet. Add something delicious and place a demo order.</div>';$('orderCount').textContent=0;return}$('ordersList').innerHTML=orders.slice().reverse().map(o=>`<article class="order-card"><div class="order-top"><div><b>${o.id}</b><small>${new Date(o.time).toLocaleString()}</small></div><span class="status-chip">${o.status}</span></div><div class="order-items">${o.items.map(i=>`${i.name} × ${i.qty}`).join(' · ')}</div><div class="order-bottom"><span>${o.area}</span><strong>${money(o.total)}</strong></div></article>`).join('');$('orderCount').textContent=orders.length}
function submitOrder(e){e.preventDefault();if(!cart.length){toast('Your cart is empty');return}const total=cart.reduce((s,x)=>s+(products.find(y=>y.id===x.id)||{price:0}).price*x.qty,0);const order={id:'PN-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'-'+String(Math.floor(Math.random()*900)+100),time:Date.now(),status:'Confirmed (demo)',name:$('customerName').value,phone:$('customerPhone').value,area:$('customerArea').value,note:$('deliveryNote').value,total,items:cart.map(x=>({id:x.id,name:products.find(y=>y.id===x.id).name,qty:x.qty}))};orders.push(order);safeStore.set('pantry-orders',orders);cart=[];persistCart();e.target.reset();closeDrawer('checkoutDrawer');closeDrawer('cartDrawer');renderOrders();toast('Demo order placed successfully')}
function renderReports(){const all=[...demoReports,...reports].sort((a,b)=>b.time-a.time);$('rescueCount').textContent=all.length;$('mapReports').textContent=Math.min(all.length,9);$('rescueFeed').innerHTML=all.slice(0,6).map(r=>`<article class="feed-card"><div class="feed-icon">${r.type==='Cat'?'🐱':r.type==='Dog'?'🐶':'🐦'}</div><div><div class="feed-line"><b>${r.type}</b><span class="severity ${r.severity.toLowerCase()}">${r.severity}</span></div><strong>${r.location}</strong><p>${r.notes}</p><small>${r.country} · ${new Date(r.time).toLocaleTimeString()}</small></div></article>`).join('')}
function setupMediaPreview(){const files=[...($('animalMedia').files||[])];$('mediaPreview').innerHTML='';files.slice(0,6).forEach(f=>{const box=document.createElement('div');box.className='media-item';if(f.type.startsWith('image/')){const img=document.createElement('img');img.alt=f.name;img.src=URL.createObjectURL(f);box.appendChild(img)}else if(f.type.startsWith('video/')){const v=document.createElement('video');v.src=URL.createObjectURL(f);v.controls=true;box.appendChild(v)}const cap=document.createElement('small');cap.textContent=f.name;box.appendChild(cap);$('mediaPreview').appendChild(box)})}
function routeUpdate(){const c=$('animalCountry').value;$('routeCountry').textContent=c;$('routeText').textContent=operators[c];$('routePriority').textContent=$('animalSeverity').value.toUpperCase();$('alertPreview').textContent=lastReport?`Prepared for ${lastReport.type} · ${lastReport.location} · ${lastReport.severity}`:'No report prepared yet.'}
function submitRescue(e){e.preventDefault();const files=[...($('animalMedia').files||[])].map(f=>({name:f.name,type:f.type}));const r={id:'R-'+Date.now(),type:$('animalType').value,severity:$('animalSeverity').value,country:$('animalCountry').value,location:$('animalLocation').value,notes:$('animalNotes').value,time:Date.now(),media:files};reports.push(r);safeStore.set('pantry-rescue-reports',reports);lastReport=r;routeUpdate();renderReports();e.target.reset();$('mediaPreview').innerHTML='';$('geoStatus').textContent='Location not set';toast('Rescue report saved. Operator alert is ready to prepare.');}
function locate(){if(!navigator.geolocation){$('geoStatus').textContent='Geolocation not supported';return}$('geoStatus').textContent='Requesting location…';navigator.geolocation.getCurrentPosition(pos=>{geo=pos.coords;$('animalLocation').value=`GPS ${pos.coords.latitude.toFixed(5)}, ${pos.coords.longitude.toFixed(5)}`;$('geoStatus').textContent='Browser location captured';$('userPin').style.left=(30+((pos.coords.longitude+180)%100)*0.3)+'%';$('userPin').style.top=(20+((90-pos.coords.latitude)%100)*0.35)+'%';$('userPin').classList.remove('hidden')},()=>{$('geoStatus').textContent='Location permission denied or unavailable'})}
function prepareAlert(){if(!lastReport){toast('Submit a rescue report first');return}routeUpdate();$('alertPreview').innerHTML=`<b>Demo alert package</b><br>${lastReport.type} · ${lastReport.severity} · ${lastReport.country}<br>${lastReport.location}<br><span>Channel: SMS / webhook placeholder</span>`;toast('Operator alert package prepared')}
function refreshAll(){updateClock();renderProducts();renderCart();renderOrders();renderReports();$('liveText').textContent='System refreshed '+nowText();toast('Pantry live mode refreshed')}
function init(){updateClock();setInterval(updateClock,1000);renderProducts();renderCart();renderOrders();renderReports();routeUpdate();
 document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));renderProducts()});
 document.querySelectorAll('.category-card').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));renderProducts();$('shop').scrollIntoView({behavior:'smooth'})});
 $('searchInput').addEventListener('input',renderProducts);$('sortSelect').addEventListener('change',renderProducts);$('cartBtn').onclick=()=>openDrawer('cartDrawer');$('checkoutBtn').onclick=()=>{if(!cart.length){toast('Your cart is empty');return}openDrawer('checkoutDrawer')};$('checkoutForm').addEventListener('submit',submitOrder);$('rescueForm').addEventListener('submit',submitRescue);$('animalMedia').addEventListener('change',setupMediaPreview);$('animalCountry').addEventListener('change',routeUpdate);$('animalSeverity').addEventListener('change',routeUpdate);$('locateBtn').onclick=locate;$('sendAlertBtn').onclick=prepareAlert;$('refreshBtn').onclick=refreshAll;$('refreshMapBtn').onclick=()=>{renderReports();toast('Rescue map refreshed')};$('clearOrdersBtn').onclick=()=>{orders=[];safeStore.set('pantry-orders',orders);renderOrders();toast('Demo orders cleared')};$('subscribeForm').addEventListener('submit',e=>{e.preventDefault();toast('Thanks. You are on the Pantry list.');e.target.reset()});$('searchBtn').onclick=()=>{$('searchInput').focus();$('shop').scrollIntoView({behavior:'smooth'})};
 $('menuBtn').onclick=()=>{const open=$('desktop-nav').classList.toggle('mobile-open');$('menuBtn').setAttribute('aria-expanded',String(open))};document.querySelectorAll('.desktop-nav a').forEach(a=>a.onclick=()=>{$('desktop-nav').classList.remove('mobile-open');$('menuBtn').setAttribute('aria-expanded','false')});
 $('overlay').onclick=closeAll;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeDrawer(b.dataset.close));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});
 }
init();
})();
