const API_BASE = (window.PANTRY_API_BASE || '').replace(/\/$/, '');
const products = [
  {id:'cat-01',name:'Daily Adult Cat Food',brand:'Purrfect Pantry Select',category:'cat',type:'Dry food',weight:'1 kg',price:790,old:850,tags:['all', 'cat', 'dry-food'],stock:'In stock',pet:'🐈',pack:'burgundy',desc:'Everyday complete dry food listing.'},
  {id:'cat-02',name:'Kitten Growth Recipe',brand:'Purrfect Pantry Select',category:'cat',type:'Kitten food',weight:'800 g',price:720,old:780,tags:['all', 'cat', 'kitten-food', 'kitten'],stock:'In stock',pet:'🐾',pack:'cream',desc:'Kitten-focused complete food listing.'},
  {id:'cat-03',name:'Indoor Cat Balance',brand:'Purrfect Pantry Select',category:'cat',type:'Dry food',weight:'1 kg',price:840,old:900,tags:['all', 'cat', 'dry-food'],stock:'Low stock',pet:'◖ᴥ◗',pack:'burgundy',desc:'Indoor adult cat food listing.'},
  {id:'cat-04',name:'Chicken Wet Cat Meal',brand:'Purrfect Pantry Select',category:'cat',type:'Wet food',weight:'400 g',price:390,old:430,tags:['all', 'cat', 'wet-food'],stock:'In stock',pet:'🐈',pack:'cream',desc:'Chicken-flavour wet meal listing.'},
  {id:'cat-05',name:'Salmon Wet Cat Meal',brand:'Purrfect Pantry Select',category:'cat',type:'Wet food',weight:'400 g',price:450,old:490,tags:['all', 'cat', 'wet-food'],stock:'In stock',pet:'🐈',pack:'burgundy',desc:'Salmon-flavour wet meal listing.'},
  {id:'cat-06',name:'Cat Creamy Treats',brand:'Purrfect Pantry Select',category:'cat',type:'Treats',weight:'60 g',price:280,old:320,tags:['all', 'cat', 'treats'],stock:'In stock',pet:'🐾',pack:'cream',desc:'Creamy treat pouch listing.'},
  {id:'dog-01',name:'Daily Adult Dog Food',brand:'Purrfect Pantry Select',category:'dog',type:'Dry food',weight:'2 kg',price:1250,old:1350,tags:['all', 'dog', 'dry-food'],stock:'In stock',pet:'🐕',pack:'burgundy',desc:'Everyday adult dog food listing.'},
  {id:'dog-02',name:'Puppy Growth Formula',brand:'Purrfect Pantry Select',category:'dog',type:'Puppy food',weight:'1.5 kg',price:1120,old:1200,tags:['all', 'dog', 'puppy-food'],stock:'In stock',pet:'🐶',pack:'cream',desc:'Puppy growth food listing.'},
  {id:'dog-03',name:'Small Breed Adult Food',brand:'Purrfect Pantry Select',category:'dog',type:'Dry food',weight:'1 kg',price:790,old:850,tags:['all', 'dog', 'dry-food'],stock:'In stock',pet:'🐕',pack:'burgundy',desc:'Small-breed adult dog food listing.'},
  {id:'dog-04',name:'Chicken Dog Wet Meal',brand:'Purrfect Pantry Select',category:'dog',type:'Wet food',weight:'400 g',price:420,old:460,tags:['all', 'dog', 'wet-food'],stock:'In stock',pet:'🐕',pack:'cream',desc:'Chicken wet dog meal listing.'},
  {id:'dog-05',name:'Dental Dog Treats',brand:'Purrfect Pantry Select',category:'dog',type:'Treats',weight:'150 g',price:390,old:430,tags:['all', 'dog', 'treats'],stock:'In stock',pet:'🐶',pack:'burgundy',desc:'Dental treat listing.'},
  {id:'bird-01',name:'Daily Budgie Seed Mix',brand:'Purrfect Pantry Select',category:'bird',type:'Seed mix',weight:'500 g',price:320,old:0,tags:['all', 'bird', 'seed-mix', 'seed'],stock:'In stock',pet:'◜•◝',pack:'cream',desc:'Daily budgerigar seed mix.'},
  {id:'bird-02',name:'Premium Finch Blend',brand:'Purrfect Pantry Select',category:'bird',type:'Seed mix',weight:'500 g',price:360,old:390,tags:['all', 'bird', 'seed-mix', 'seed'],stock:'In stock',pet:'◠•◠',pack:'burgundy',desc:'Finch seed blend listing.'},
  {id:'bird-03',name:'Bird Daily Essentials',brand:'Purrfect Pantry Select',category:'bird',type:'Daily feed',weight:'1 kg',price:590,old:0,tags:['all', 'bird', 'daily-feed'],stock:'In stock',pet:'•ᴗ•',pack:'cream',desc:'Daily companion-bird feed.'},
  {id:'bird-04',name:'Cockatiel Premium Mix',brand:'Purrfect Pantry Select',category:'bird',type:'Seed mix',weight:'1 kg',price:690,old:740,tags:['all', 'bird', 'seed-mix', 'seed'],stock:'In stock',pet:'◜•◝',pack:'burgundy',desc:'Cockatiel seed mix listing.'},
  {id:'bird-05',name:'Millet Spray Pack',brand:'Purrfect Pantry Select',category:'bird',type:'Treats',weight:'250 g',price:240,old:280,tags:['all', 'bird', 'treats'],stock:'In stock',pet:'✦',pack:'cream',desc:'Millet treat listing.'},
  {id:'fish-01',name:'Tropical Fish Flakes',brand:'Purrfect Pantry Select',category:'fish',type:'Fish food',weight:'100 g',price:260,old:290,tags:['all', 'fish', 'fish-food'],stock:'In stock',pet:'🐟',pack:'burgundy',desc:'Tropical fish flake food.'},
  {id:'fish-02',name:'Goldfish Floating Pellets',brand:'Purrfect Pantry Select',category:'fish',type:'Fish food',weight:'100 g',price:230,old:260,tags:['all', 'fish', 'fish-food'],stock:'In stock',pet:'🐠',pack:'cream',desc:'Goldfish floating pellet food.'},
  {id:'fish-03',name:'Cichlid Protein Pellets',brand:'Purrfect Pantry Select',category:'fish',type:'Fish food',weight:'250 g',price:520,old:570,tags:['all', 'fish', 'fish-food'],stock:'In stock',pet:'🐟',pack:'burgundy',desc:'Cichlid pellet food listing.'},
  {id:'rabbit-01',name:'Rabbit Daily Timothy Mix',brand:'Purrfect Pantry Select',category:'rabbit',type:'Rabbit food',weight:'1 kg',price:520,old:570,tags:['all', 'rabbit', 'rabbit-food'],stock:'In stock',pet:'🐇',pack:'cream',desc:'Daily rabbit feed listing.'},
  {id:'rabbit-02',name:'Rabbit Hay Premium',brand:'Purrfect Pantry Select',category:'rabbit',type:'Hay',weight:'500 g',price:390,old:430,tags:['all', 'rabbit', 'hay'],stock:'In stock',pet:'🐇',pack:'burgundy',desc:'Premium hay listing.'},
  {id:'hamster-01',name:'Hamster Complete Mix',brand:'Purrfect Pantry Select',category:'hamster',type:'Small pet food',weight:'500 g',price:360,old:400,tags:['all', 'hamster', 'small-pet-food'],stock:'In stock',pet:'🐹',pack:'cream',desc:'Complete hamster food mix.'},
  {id:'hamster-02',name:'Hamster Crunch Treats',brand:'Purrfect Pantry Select',category:'hamster',type:'Treats',weight:'150 g',price:250,old:290,tags:['all', 'hamster', 'treats'],stock:'In stock',pet:'🐹',pack:'burgundy',desc:'Small-pet treat listing.'},
  {id:'treat-01',name:'Mixed Pet Training Bites',brand:'Purrfect Pantry Select',category:'treats',type:'Treats',weight:'200 g',price:420,old:460,tags:['all', 'treats', 'treats'],stock:'In stock',pet:'★',pack:'cream',desc:'Training treat listing for suitable pets.'},
  {id:'treat-02',name:'Natural Chicken Jerky Bites',brand:'Purrfect Pantry Select',category:'treats',type:'Treats',weight:'100 g',price:450,old:500,tags:['all', 'treats', 'treats'],stock:'In stock',pet:'★',pack:'burgundy',desc:'Natural-style chicken treat listing.'}
];
const safeStorage=(()=>{try{return window.localStorage}catch(e){return {getItem:()=>null,setItem:()=>{}}}})();
let savedCart={}; try{savedCart=JSON.parse(safeStorage.getItem('pp-cart')||'{}')||{}}catch(e){savedCart={};}
const state={filter:'all',query:'',cart:savedCart,pricesLoaded:false,checkoutSession:null};
const money=n=>`৳${Number(n||0).toLocaleString('en-BD')}`;
const el=s=>document.querySelector(s); const els=s=>[...document.querySelectorAll(s)];
async function api(path,options={}){ if(!API_BASE) throw new Error('API_NOT_CONFIGURED'); const r=await fetch(API_BASE+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.message||data.error||`HTTP_${r.status}`); return data; }
async function loadPrices(){try{const data=await api('/api/products'); if(Array.isArray(data.products)){data.products.forEach(remote=>{const p=products.find(x=>x.id===remote.id); if(p){p.price=Number(remote.price);p.old=Number(remote.old||0);p.stock=remote.stockLabel||p.stock;}}); state.pricesLoaded=true; renderProducts();renderCart();}}catch(e){/* static fallback keeps storefront usable */}}
function saveCart(){safeStorage.setItem('pp-cart',JSON.stringify(state.cart)); renderCartCount(); renderCart();}
function cartQty(){return Object.values(state.cart).reduce((a,b)=>a+b,0)}
function renderCartCount(){el('#cartCount').textContent=cartQty()}
function filteredProducts(){const q=state.query.trim().toLowerCase(); return products.filter(p=>{const matchesFilter=p.tags.includes(state.filter); if(!matchesFilter)return false; if(!q)return true; const haystack=[p.name,p.brand,p.category,p.type,p.weight,p.desc,p.pet].join(' ').toLowerCase(); return haystack.includes(q);})}
function productVisual(p,large=false){return `<div class="${large?'product-detail-media':''} ${large?'':'product-media '+(p.category==='bird'?'bird':'')}"><div class="pack ${p.pack==='cream'?'cream':''}"><div><div class="mini-pet">${p.pet}</div><div class="mini-brand">Purrfect<br/>Pantry</div></div></div></div>`}
function renderProducts(){const grid=el('#productGrid'), empty=el('#emptyState'); const list=filteredProducts(); const countLabel=el('#catalogSearchHint'); if(countLabel){countLabel.textContent=state.query.trim()?`${list.length} matching listing${list.length===1?'':'s'} · Search covers food name, pet type, flavour, brand and pack size.`:`${products.length} food listings · Try “cat”, “chicken”, “1 kg” or a product name.`;} const clear=el('#catalogSearchClear'); if(clear)clear.hidden=!state.query.trim(); grid.innerHTML=list.map(p=>`<article class="product-card"><button class="product-media-wrap" data-view="${p.id}" aria-label="View ${p.name}" style="all:unset;cursor:pointer">${productVisual(p)}</button><div class="product-body"><div class="meta"><span>${p.brand}</span><span>·</span><span>${p.weight}</span></div><h3>${p.name}</h3><div class="meta"><span>${p.type}</span><span>·</span><span class="stock">${p.stock}</span></div><div class="price-row"><div><span class="price">${money(p.price)}</span>${p.old?`<span class="old">${money(p.old)}</span>`:''}</div></div><div class="card-actions"><button class="btn outline" data-view="${p.id}">Details</button><button class="btn btn-primary" data-add="${p.id}">Add to bag</button><button class="btn buy-now" data-buy="${p.id}">Buy now</button></div></div></article>`).join(''); empty.hidden=list.length>0; grid.hidden=list.length===0; els('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.add))); els('[data-buy]').forEach(b=>b.addEventListener('click',()=>buyNow(b.dataset.buy))); els('[data-view]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.view)));}
function addToCart(id){state.cart[id]=(state.cart[id]||0)+1;saveCart();toast('Added to your bag');}
function buyNow(id){state.cart[id]=(state.cart[id]||0)+1;saveCart();openCheckout();}
function removeFromCart(id){delete state.cart[id];saveCart()}
function changeQty(id,d){state.cart[id]=Math.max(1,(state.cart[id]||1)+d);saveCart()}
function renderCart(){const wrap=el('#cartItems'); const entries=Object.entries(state.cart); if(!entries.length){wrap.innerHTML='<div class="empty-state">Your bag is ready for its first pick.</div>';el('#cartSubtotal').textContent=money(0);return}let total=0;wrap.innerHTML=entries.map(([id,q])=>{const p=products.find(x=>x.id===id); if(!p)return ''; total+=p.price*q; return `<div class="cart-item"><div class="cart-thumb"><span>${p.pet}</span></div><div><h4>${p.name}</h4><p>${p.weight} · ${money(p.price)}</p><div class="qty"><button data-minus="${id}">−</button><span>${q}</span><button data-plus="${id}">+</button><button class="text-btn" data-remove="${id}">Remove</button></div></div><strong>${money(p.price*q)}</strong></div>`}).join('');el('#cartSubtotal').textContent=money(total);els('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));els('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));els('[data-remove]').forEach(b=>b.onclick=()=>removeFromCart(b.dataset.remove));}
function openCart(){el('#cartDrawer').classList.add('open');el('#cartDrawer').setAttribute('aria-hidden','false');el('#scrim').hidden=false}
function closeCart(){el('#cartDrawer').classList.remove('open');el('#cartDrawer').setAttribute('aria-hidden','true');el('#scrim').hidden=true}
function openProduct(id){const p=products.find(x=>x.id===id);el('#productModalBody').innerHTML=`<div class="product-modal-grid">${productVisual(p,true)}<div class="product-detail-copy"><p class="eyebrow">${({cat:'Cat Food',dog:'Dog Food',bird:'Bird Food',fish:'Fish Food',rabbit:'Rabbit Food',hamster:'Hamster Food',treats:'Treats'}[p.category]||'Pet Food')} · ${p.weight}</p><h2>${p.name}</h2><p>${p.desc}</p><div class="price-row"><div><span class="price">${money(p.price)}</span>${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><span class="stock">${p.stock}</span></div><div class="hero-ctas"><button class="btn btn-primary" id="modalAdd">Add to bag</button><button class="btn outline" id="modalBuy">Buy now</button></div></div></div>`;el('#modalAdd').onclick=()=>{addToCart(id);el('#productModal').close()};el('#modalBuy').onclick=()=>{el('#productModal').close();buyNow(id)};el('#productModal').showModal()}
function openCheckout(){if(!cartQty()){toast('Add at least one item first');return}renderCheckout();el('#checkoutModal').showModal()}
function renderCheckout(){let total=0;el('#checkoutSummary').innerHTML=Object.entries(state.cart).map(([id,q])=>{const p=products.find(x=>x.id===id);total+=p.price*q;return `<div class="checkout-line"><span>${p.name} × ${q}</span><strong>${money(p.price*q)}</strong></div>`}).join('');el('#checkoutTotal').textContent=money(total)}
function validBDPhone(v){return /^(?:\+8801|8801|01)\d{9}$/.test(v.replace(/[\s-]/g,''))}
function normalizeBDPhone(v){let s=v.replace(/[\s-]/g,''); if(s.startsWith('+880')) return s.slice(1); if(s.startsWith('880')) return s; return '880'+s.slice(1)}
function setOtpStage(show){el('#otpStage').hidden=!show;el('#checkoutStage').hidden=show; if(show) el('#otpInput').focus()}
async function sendOtp(){const form=el('#checkoutForm'); const phone=normalizeBDPhone(form.phone.value); if(!validBDPhone(form.phone.value)){toast('Enter a valid Bangladesh mobile number');return false} if(!API_BASE){toast('OTP server is not configured yet');return false} try{const data=await api('/api/otp/send',{method:'POST',body:JSON.stringify({phone})});state.checkoutSession={phone,otpToken:data.otpToken}; setOtpStage(true); toast('OTP sent to your mobile number'); return true}catch(e){toast(e.message||'Could not send OTP');return false}}
async function verifyOtp(){const code=el('#otpInput').value.trim(); if(!/^\d{6}$/.test(code)){toast('Enter the 6-digit OTP');return} try{const data=await api('/api/otp/verify',{method:'POST',body:JSON.stringify({otpToken:state.checkoutSession.otpToken,phone:state.checkoutSession.phone,code})}); if(data.verified){await placeVerifiedOrder(data.verificationToken);}}catch(e){toast(e.message||'OTP verification failed')}}
async function placeVerifiedOrder(verificationToken){const fd=new FormData(el('#checkoutForm')); const items=Object.entries(state.cart).map(([id,q])=>({id,qty:q})); try{const data=await api('/api/orders',{method:'POST',body:JSON.stringify({verificationToken,customer:{name:fd.get('name'),phone:normalizeBDPhone(fd.get('phone')),address:fd.get('address'),payment:fd.get('payment')},items})}); safeStorage.setItem('pp-last-order',JSON.stringify(data.order));state.cart={};saveCart();el('#checkoutModal').close();toast(`Order ${data.order.orderId} confirmed`);el('#checkoutForm').reset();el('#otpInput').value='';setOtpStage(false);}catch(e){toast(e.message||'Could not create order')}}
function toast(msg){const t=el('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3000)}
document.addEventListener('DOMContentLoaded',()=>{
 el('#year').textContent=new Date().getFullYear(); renderProducts(); renderCartCount(); renderCart(); loadPrices();
 els('.filter').forEach(b=>b.onclick=()=>{els('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderProducts();document.querySelector('#featured').scrollIntoView({behavior:'smooth'});});
 els('.filter-cat').forEach(b=>b.onclick=()=>{state.filter='cat';els('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='cat'));renderProducts();el('#featured').scrollIntoView({behavior:'smooth'});});
 els('.filter-bird').forEach(b=>b.onclick=()=>{state.filter='bird';els('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='bird'));renderProducts();el('#featured').scrollIntoView({behavior:'smooth'});});
 el('#searchToggle').onclick=()=>{el('#searchBar').hidden=false;el('#searchInput').value=state.query;el('#searchInput').focus()}; el('#searchClose').onclick=()=>{el('#searchBar').hidden=true}; el('#searchInput').oninput=e=>{state.query=e.target.value;el('#catalogSearchInput').value=state.query;renderProducts()}; el('#catalogSearchInput').oninput=e=>{state.query=e.target.value;el('#searchInput').value=state.query;renderProducts()}; el('#catalogSearchClear').onclick=()=>{state.query='';el('#catalogSearchInput').value='';el('#searchInput').value='';renderProducts();el('#catalogSearchInput').focus()};
 el('#cartOpen').onclick=openCart; el('#cartClose').onclick=closeCart; el('#scrim').onclick=closeCart; el('#clearCart').onclick=()=>{state.cart={};saveCart();toast('Bag cleared')};
 el('#productModalClose').onclick=()=>el('#productModal').close(); el('#checkoutOpen').onclick=()=>{closeCart();openCheckout()}; el('#checkoutClose').onclick=()=>el('#checkoutModal').close();
 el('#checkoutForm').onsubmit=async e=>{e.preventDefault(); await sendOtp()}; el('#verifyOtpBtn').onclick=verifyOtp; el('#resendOtpBtn').onclick=sendOtp;
 el('#newsletterForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Thanks. Newsletter capture is ready for your provider.')};
 el('.mobile-menu-btn').onclick=()=>{const n=el('#mobileNav');n.hidden=!n.hidden;el('.mobile-menu-btn').setAttribute('aria-expanded',String(!n.hidden))}; els('#mobileNav a').forEach(a=>a.onclick=()=>{el('#mobileNav').hidden=true});
});
