const products = [
  {id:'cat-01',name:'Daily Adult Cat Food',brand:'Purrfect Pantry Select',category:'cat',type:'Dry food',weight:'1 kg',price:790,old:850,tags:['all','cat'],stock:'In stock',pet:'🐈',pack:'burgundy',desc:'A straightforward everyday dry-food shelf starter for adult cats.'},
  {id:'cat-02',name:'Kitten Growth Recipe',brand:'Purrfect Pantry Select',category:'cat',type:'Kitten food',weight:'800 g',price:720,old:0,tags:['all','cat','kitten'],stock:'In stock',pet:'🐾',pack:'cream',desc:'A kitten-focused product slot for a future verified recipe and label.'},
  {id:'cat-03',name:'Indoor Cat Balance',brand:'Purrfect Pantry Select',category:'cat',type:'Dry food',weight:'1 kg',price:840,old:900,tags:['all','cat'],stock:'Low stock',pet:'◖ᴥ◗',pack:'burgundy',desc:'A premium-looking product slot ready for a verified indoor-cat formula.'},
  {id:'bird-01',name:'Daily Budgie Seed Mix',brand:'Purrfect Pantry Select',category:'bird',type:'Seed mix',weight:'500 g',price:320,old:0,tags:['all','bird','seed'],stock:'In stock',pet:'◜•◝',pack:'cream',desc:'A clean seed-mix shelf slot for companion birds.'},
  {id:'bird-02',name:'Premium Finch Blend',brand:'Purrfect Pantry Select',category:'bird',type:'Seed mix',weight:'500 g',price:360,old:390,tags:['all','bird','seed'],stock:'In stock',pet:'◠•◠',pack:'burgundy',desc:'A refined bird-feed listing ready for verified product specifications.'},
  {id:'bird-03',name:'Bird Daily Essentials',brand:'Purrfect Pantry Select',category:'bird',type:'Daily feed',weight:'1 kg',price:590,old:0,tags:['all','bird'],stock:'In stock',pet:'•ᴗ•',pack:'cream',desc:'A scalable bird-food listing designed for future supplier integration.'},
];

const safeStorage=(()=>{try{return window.localStorage}catch(e){return {getItem:()=>null,setItem:()=>{}}}})();
let savedCart={};
try{savedCart=JSON.parse(safeStorage.getItem('pp-cart')||'{}')||{}}catch(e){savedCart={};}
const state={filter:'all',query:'',cart:savedCart};
const money=n=>`৳${n.toLocaleString('en-BD')}`;
const el=s=>document.querySelector(s); const els=s=>[...document.querySelectorAll(s)];
function saveCart(){safeStorage.setItem('pp-cart',JSON.stringify(state.cart)); renderCartCount(); renderCart();}
function cartQty(){return Object.values(state.cart).reduce((a,b)=>a+b,0)}
function renderCartCount(){el('#cartCount').textContent=cartQty()}
function filteredProducts(){return products.filter(p=>p.tags.includes(state.filter) && `${p.name} ${p.brand} ${p.type} ${p.weight}`.toLowerCase().includes(state.query.toLowerCase()))}
function productVisual(p,large=false){return `<div class="${large?'product-detail-media':''} ${large?'':'product-media '+(p.category==='bird'?'bird':'')}"><div class="pack ${p.pack==='cream'?'cream':''}"><div><div class="mini-pet">${p.pet}</div><div class="mini-brand">Purrfect<br/>Pantry</div></div></div></div>`}
function renderProducts(){const grid=el('#productGrid'), empty=el('#emptyState'); const list=filteredProducts(); grid.innerHTML=list.map(p=>`<article class="product-card"><button class="product-media-wrap" data-view="${p.id}" aria-label="View ${p.name}" style="all:unset;cursor:pointer">${productVisual(p)}</button><div class="product-body"><div class="meta"><span>${p.brand}</span><span>·</span><span>${p.weight}</span></div><h3>${p.name}</h3><div class="meta"><span>${p.type}</span><span>·</span><span class="stock">${p.stock}</span></div><div class="price-row"><div><span class="price">${money(p.price)}</span>${p.old?`<span class="old">${money(p.old)}</span>`:''}</div></div><div class="card-actions"><button class="btn outline" data-view="${p.id}">Details</button><button class="btn btn-primary" data-add="${p.id}">Add to bag</button><button class="btn buy-now" data-buy="${p.id}">Buy now</button></div></div></article>`).join(''); empty.hidden=list.length>0; grid.hidden=list.length===0; els('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.add))); els('[data-buy]').forEach(b=>b.addEventListener('click',()=>buyNow(b.dataset.buy))); els('[data-view]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.view)));}
function addToCart(id){state.cart[id]=(state.cart[id]||0)+1;saveCart();toast('Added to your bag');}
function buyNow(id){state.cart[id]=(state.cart[id]||0)+1;saveCart();openCheckout();}
function removeFromCart(id){delete state.cart[id];saveCart()}
function changeQty(id,d){state.cart[id]=Math.max(1,(state.cart[id]||1)+d);saveCart()}
function renderCart(){const wrap=el('#cartItems'); const entries=Object.entries(state.cart); if(!entries.length){wrap.innerHTML='<div class="empty-state">Your bag is ready for its first pick.</div>';el('#cartSubtotal').textContent=money(0);return}let total=0;wrap.innerHTML=entries.map(([id,q])=>{const p=products.find(x=>x.id===id); if(!p)return ''; total+=p.price*q; return `<div class="cart-item"><div class="cart-thumb"><span>${p.pet}</span></div><div><h4>${p.name}</h4><p>${p.weight} · ${money(p.price)}</p><div class="qty"><button data-minus="${id}">−</button><span>${q}</span><button data-plus="${id}">+</button><button class="text-btn" data-remove="${id}">Remove</button></div></div><strong>${money(p.price*q)}</strong></div>`}).join('');el('#cartSubtotal').textContent=money(total);els('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));els('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));els('[data-remove]').forEach(b=>b.onclick=()=>removeFromCart(b.dataset.remove));}
function openCart(){el('#cartDrawer').classList.add('open');el('#cartDrawer').setAttribute('aria-hidden','false');el('#scrim').hidden=false}
function closeCart(){el('#cartDrawer').classList.remove('open');el('#cartDrawer').setAttribute('aria-hidden','true');el('#scrim').hidden=true}
function openProduct(id){const p=products.find(x=>x.id===id);el('#productModalBody').innerHTML=`<div class="product-modal-grid">${productVisual(p,true)}<div class="product-detail-copy"><p class="eyebrow">${p.category==='cat'?'Cat Food':'Bird Food'} · ${p.weight}</p><h2>${p.name}</h2><p>${p.desc}</p><div class="price-row"><div><span class="price">${money(p.price)}</span>${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><span class="stock">${p.stock}</span></div><div class="hero-ctas"><button class="btn btn-primary" id="modalAdd">Add to bag</button><button class="btn outline" id="modalBuy">Buy now</button></div></div></div>`;el('#modalAdd').onclick=()=>{addToCart(id);el('#productModal').close()};el('#modalBuy').onclick=()=>{el('#productModal').close();buyNow(id)};el('#productModal').showModal();}
function openCheckout(){if(!cartQty()){toast('Add at least one item first');return}renderCheckout();el('#checkoutModal').showModal()}
function renderCheckout(){let total=0;el('#checkoutSummary').innerHTML=Object.entries(state.cart).map(([id,q])=>{const p=products.find(x=>x.id===id);total+=p.price*q;return `<div class="checkout-line"><span>${p.name} × ${q}</span><strong>${money(p.price*q)}</strong></div>`}).join('');el('#checkoutTotal').textContent=money(total)}
function toast(msg){const t=el('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2300)}

document.addEventListener('DOMContentLoaded',()=>{
  el('#year').textContent=new Date().getFullYear(); renderProducts(); renderCartCount(); renderCart();
  els('.filter').forEach(b=>b.onclick=()=>{els('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderProducts();document.querySelector('#featured').scrollIntoView({behavior:'smooth'});});
  els('.filter-cat').forEach(b=>b.onclick=()=>{state.filter='cat';els('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='cat'));renderProducts();el('#featured').scrollIntoView({behavior:'smooth'});});
  els('.filter-bird').forEach(b=>b.onclick=()=>{state.filter='bird';els('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='bird'));renderProducts();el('#featured').scrollIntoView({behavior:'smooth'});});
  el('#searchToggle').onclick=()=>{el('#searchBar').hidden=false;el('#searchInput').focus()}; el('#searchClose').onclick=()=>{el('#searchBar').hidden=true}; el('#searchInput').oninput=e=>{state.query=e.target.value;renderProducts()};
  el('#cartOpen').onclick=openCart; el('#cartClose').onclick=closeCart; el('#scrim').onclick=closeCart; el('#clearCart').onclick=()=>{state.cart={};saveCart();toast('Bag cleared')};
  el('#productModalClose').onclick=()=>el('#productModal').close(); el('#checkoutOpen').onclick=()=>{closeCart();openCheckout()}; el('#checkoutClose').onclick=()=>el('#checkoutModal').close();
  el('#checkoutForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);let total=0;const items=Object.entries(state.cart).map(([id,q])=>{const p=products.find(x=>x.id===id);if(!p)return null;total+=p.price*q;return {id,name:p.name,qty:q,unitPrice:p.price,weight:p.weight,category:p.category};}).filter(Boolean);const order={orderId:'PP-'+Date.now().toString().slice(-8),createdAt:new Date().toISOString(),customer:Object.fromEntries(fd.entries()),items,total};safeStorage.setItem('pp-last-order',JSON.stringify(order));state.cart={};saveCart();el('#checkoutModal').close();toast('Order request saved locally. Connect your live order channel before launch.');e.target.reset();};
  el('#newsletterForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Thanks. Newsletter capture is ready for your provider.');};
  el('.mobile-menu-btn').onclick=()=>{const n=el('#mobileNav');n.hidden=!n.hidden;el('.mobile-menu-btn').setAttribute('aria-expanded',String(!n.hidden));};
  els('#mobileNav a').forEach(a=>a.onclick=()=>{el('#mobileNav').hidden=true;});
});
